### ISSUE TITLE
Hardcoded filepaths

### ISSUE THREAD

**Issue by ammgws** [WnndGws/Locutus#1]
All the filenames and filepaths are hardcoded so I cannot use the script. Did you mean to push to gists.github.com instead of here?

**Comment by WnndGws** [comment]
It is a bash script, so run it in terminal

I will warn that it is nowhere near ready, and i strongly advise against using it at this stage if you didnt know how to run a .sh file.

Marking as closed since project only just started, and stupid question

**Comment by ammgws** [comment]
The error I get is "No such file or directory". Something about a why-man or some kind of measurement?

**Comment by WnndGws** [comment]
Again.... This repo isn't ready for public. Wait for a 1.x release. Until it is ready use the individual apps I call in the script if you need to backup

**Comment by ammgws** [comment]
Thank you for the prompt response. I appreciate your professionalism regarding this matter.
